server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springtest?serverTimezone=GMT
    username: root
    password: hmz990203
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    thymeleaf:
      cache: false